import { TripDetail } from "@/lib/types";
export const navlinks = [
  {
    id: "1",
    name: "Packages",
    link: "/packages",
  },
  {
    id: "2",
    name: "Destinations",
    link: "/destinations",
  },
  {
    id: "3",
    name: "Blog",
    link: "/blog",
  },
  {
    id: "4",
    name: "About Us",
    link: "/About",
  },
  {
    id: "5",
    name: "Contact",
    link: "/Contact",
  },
];

export const team = [
  {
    id: "1",
    image: "team1",
    name: "Rajen Rai",
    role: "Co-Founder/Marketing Head",
  },
  {
    id: "2",
    image: "team2",
    name: "Topden Gurung",
    role: "Co-Founder/Operations Head",
  },
  {
    id: "3",
    image: "team3",
    name: "Prabesh Subba",
    role: "Co-Founder/Accounts Head",
  },
];

export const placesAndDestinations: { [key: string]: string[] } = {
  Sikkim: [
    "Gangtok",
    "Pelling",
    "Yuksom",
    "Zuluk",
    "Lachen",
    "Ravangla",
    "Namchi",
    "Lachung",
    "Chungthang",
    "Temi Tarku",
    "Aritar",
    "Gurudongmar Lake",
  ],
  "North Bengal": [
    "Mirik",
    "Lava and Loleygaon",
    "Darjeeling",
    "Sittong",
    "Rishyap",
    "Kurseong",
    "Kalimpong",
    "Sillerygaon",
    "Singalila Range Trek",
  ],
  "Arunachal Pradesh": [
    "Aalo",
    "Bomdila",
    "Dirang",
    "Eaglenest",
    "Itanagar",
    "Menchukha",
    "Namsai",
    "Pasighat",
    "Roing",
    "Tawang",
    "Tuting",
    "Walong",
    "Ziro",
  ],
  Nagaland: [
    "Benreu",
    "Chizami",
    "Dimapur",
    "Doyang",
    "Khezhakeno Village",
    "Khonoma",
    "Kohima",
    "Mokokchung",
    "Mon",
    "Pfütsero",
    "Shilloi",
    "Dzukou Valley",
    "Tseminyu",
  ],
  Meghalaya: [
    "Shillong",
    "Cherrapunji",
    "Mawlynnong",
    "Tura",
    "Jowai",
    "Shnongpdeng",
    "Dawki",
    "Phe Phe Waterfall",
  ],
  Bhutan: [
    "Paro valley",
    "Thimphu",
    "Bhuthang Valley",
    "Phobjika Valley",
    "Dochula Pass",
    "Wangdue Phodrang",
    "Trongsa",
    "Lhuentse",
    "Trashingang",
    "Samdrup Jongkhar",
    "Laya",
    "Gasa",
    "Pemagatshel",
    "Punakha",
    "Phuentsholing"
  ],
};
