import { TripDetail } from "@/lib/types";

export const UPCOMING_SIKKIMDARJ = {
    id: "6",
    image: "images/sikkimdarj/2",
    cover:"images/sikkimdarj/sikkimdarj",
    title: "Experience Sikkim & Darjeeling",
    pdf:"pdf/ExperienceSikkimDarjeeling",
    desc: "Sikkim, A gem of North East, is renowned for its unrivalled excellence and stunning beauty. Sikkim is situated in the immaculate characteristic magnificence of the Himalayas, wedged between Nepal, Bhutan, and Tibet. This all-around improved custom visit is a blend of tranquilly and harmony through which you can investigate the astounding excellence of this Himalayan slope region. Darjeeling, also known as the Queen of the Hills, is equally enchanting. It's a beautiful Victorian town known for its Buddhist monasteries and temples, as well as its mountain scenery.",
    durationn: "6",
    durationd: "7",
    originalPrice:"24,900",
    currentPrice:"22,900",
    costDouble: "",
    link: "upcoming-sikkim-darjeeling",
    photoGalleries: [
      {
        title: "sikkimdarj",
        images: "images/sikkimdarj/1",
      },
      {
        title: "sikkimdarj",
        images: "images/sikkimdarj/2",
      },
      {
        title: "sikkimdarj",
        images: "images/sikkimdarj/3",
      },
      {
        title: "sikkimdarj",
        images: "images/sikkimdarj/4",
      },
      {
        title: "sikkimdarj",
        images: "images/sikkimdarj/5",
      },
    ],
    tourDates: ["19th October - 25th October","9th November - 25th November","7th December - 13th December"],
    detailedItinerary: [
      {
        day: "Day 1",
        title: "Arrival in Siliguri and Transfer to Gangtok",
        activities: [
          "Upon arrival at  Siliguri you will be warmly greeted by our representative. From here, you will board our comfortable vehicle and commence your journey to Gangtok.",
          "During the drive, you will make a brief stop at the Triveni View Point, where you can witness the stunning confluence of the Teesta and Rangeet rivers.",
          "Enjoy the scenic drive to Gangtok, navigating through the winding roads along the picturesque Teesta River.",
          "In the evening, you will have the opportunity to visit MG Marg on your own and explore the vibrant local atmosphere.",
          "Arrive in Gangtok and check into your hotel for an overnight stay.",
        ],
      },
      {
        day: "Day 2",
        title: "Excursions to Tsomgo lake and  Nathula Pass",
        activities: [
         "After breakfast, we will embark on a full-day excursion exploring the beautiful surroundings of Gangtok.",
         "Our first stop will be the glacial Tsomgo Lake, also known as Changu Lake. This stunning lake is renowned for its scenic beauty and ever-changing colors.",
         "Next, we will drive to the Baba Mandir, a shrine dedicated to Baba Harbhajan Singh, a revered soldier of the Indian Army.",
         "We will then visit Nathula Pass, an Indo-China border post (Note: Nathula Pass is closed on Mondays).",
         "After an eventful day, we will return to Gangtok for an overnight stay at your hotel.",
        ],
      },
      {
        day: "Day 3",
        title: "Transfer from Gangtok to Pelling via Ravangla or Namchi",
        activities: [
         "After breakfast, enjoy a comfortable transfer from Gangtok to Pelling via Ravangla OR Namchi.",
         "On the way, stop by Buddha Park and witness the 130 ft. High Shakyamuni Buddha Statue.",
         "OR visit the Namchi Chardham and witness the 108 ft. High Statue of Lord Shiva encircled and supported by a girdle of Chardham, which are situated in India at four different places, in East as Jagannath, West as Dwarika, South as Rameshwaram, and North as Badrinath.",
         "As you drive towards Pelling witness the beauty of the Kanchenjunga Ranges.",
         "Upon reaching, check-in to the hotel/homestay for an overnight stay.",
        ],
      },
      {
        day: "Day 4",
        title: "Pelling full day sightseeing",
        activities: [
          "After a hearty breakfast, indulge in an immersive City tour of Pelling.",
          "Head to the sacred Khecheopalri Lake which is also known as the wish-fulfilling lake and has religious significance in both Hindu and Buddhist folklore.",
          "Further sightseeing will include a visit to some of the most scenic waterfalls like Rimbi Waterfalls and the Kanchenjunga Waterfall.",
          "Later, seek blessings of the local deities by visiting the Pemayangtse Monastery.",
          "Visit the Rabdentse Ruins to know about the glorious past of Sikkim.",
          "Other sightseeing places for the day include Bird Sanctuary, Darap Valley,Skywalk & Rimbi Orange Garden.",
          "Return back to the hotel, after a day full of sightseeing for an overnight stay.",
        ],
      },
      {
        day: "Day 5",
        title: "Transfer from Pelling to Darjeeling",
        activities: [
          "After having a flavourful breakfast, you will start from Pelling to Darjeeling.",
          "Travel through the trails decorated with the magical views of the Himalayas and the adjoining valleys and don’t forget to capture the amazing snow-covered peaks lined with Tea Gardens.",
          "Reach Darjeeling and check-in to the hotel, and spend the rest of the evening at leisure.",
          "You can also explore the bustling Mall Road in Darjeeling and buy some unique souvenirs and handicrafts.",
          "Overnight stay at the hotel."
        ],
      },
      {
        day: "Day 6",
        title: "Sightseeing in Darjeeling",
        activities: [
          "Starting the day with an amazing experience, you will be starting early in the morning,at around 4 AM. Climb up to the top of the Tiger Hill to catch the sunrise casting golden lights on Kanchenjunga",
          "Following this experience will be the visit to the famous Batasia Loop and Ghoom Monastery.",
          "Return and enjoy a delicious breakfast before proceeding onwards with more local sightseeing.",
          "You will be covering attractions like the Zoological Park, Himalayan Mountaineering Institute, Ropeway, Tibetan Refugee Self Help Centre, Tenzing Rock, and Japanese Temple",
          "Overnight at the hotel."
        ],
      },
      {
        day: "Day 7",
        title: "Departure Day",
        activities: [
          "After breakfast, proceed for Siliguri.",
          "Board your train/flight for your destination with unforgettable memories.",
          "Have a great journey towards your hometown.",
        ],
      },
    ],
    knowBeforeYouGo: [
      "ID proof is mandatory for each guest at booking and arrival. PAN and Aadhar are not valid address proof. Follow State Government guidelines. Maintain social distancing, sanitize frequently, and use masks.",
      "Offbeatsikkim reserves the right to change the itinerary due to natural calamities, weather, or roadblocks. We provide a standard room in the booked category.",
      "As per North East guidelines, vehicles are not on disposal and cannot deviate from the itinerary unless issues occur. Transport is point-to-point only. Sumo/Bolero vehicles are not allowed in the main market area from 8 AM to 8 PM.",
      "Offbeatsikkim will provide accommodation from the shared list or a similar hotel in the booked category. We will inform you about any changes in advance.",
      "Heavy rainfall between June and September may cause real-time itinerary changes. Offbeatsikkim will arrange alternate sightseeing, but the cost of alternative accommodation must be borne by the customer.",
      "In case of unforeseen weather or government restrictions, certain activities may be canceled. A refund may not be applicable, and we are not responsible for costs arising from unforeseen circumstances.",
      "Foreigners cannot visit Baba Mandir. Offbeatsikkim is not liable for refunds or discounts if sightseeing is not completed due to various reasons beyond control.",
      "Real-time cancellations are not entertained. Rescheduling is treated as cancellation, with 100% of the tour cost charged as a cancellation fee.",
      "Cancellation policies are as stated on the website. GST is applicable. Airfare, train fare, and bus fare are not included. The traveler must take care of international airfare, visa fees, airport tax, and insurance",
      "Do not consume alcohol or intoxicants during the tour. Do not litter at local sites or campsites."
    ],
    inclusions: [
      "Entire travel as per the itinerary in a private vehicle",
      "6 Nights accommodation (2nights stay in Gangtok, 2 nights stay in Pelling and 2 Nights in Darjeeling) on double/ triple sharing. Note- Single occupancy accommodation is available for an additional cost of 2500/-",
      "A total of 12 meals ( Dinner on Day 1, Breakfast and Dinner on Day 2, Breakfast and Dinner on Day 3, Breakfast and Dinner on Day 4 , Breakfast and Dinner on Day 5 Breakfast and dinner , On Day 6 Breakfast and Dinner ,and Breakfast on Day7)",
      "All inner line permit if anything applicable",
      "Driver Allowances and fuels",
      "Parking.",
      "Permit for Tsomgo Lake , Baba Mandir and Nathula pass.",
      "Extra cost for Nathula pass included.",
    ],
    exclusions: [
     "GST (5%) is applicable extra.",
     "Any kind of food and beverages that is not included in the package like alcohol drinks, mineral water, meals/refreshment/lunches on the highway.",
     "Any personal expense like tip to the drivers, entry to the monuments, monasteries, camera/video camera charges, laundry, telephone bills, tips etc.",
     "Any cost arising due to natural calamities like landslides, roadblocks,Route diversion etc. (to be borne by the customer on the spot)",
     "Anything not mentioned in the inclusion.",
     " Air fares/Train Tickets.",
    ],
    bookingProcess: [
      "To confirm your booking, a deposit of INR5000 Per Head is required in advance.",
      "The remaining amount must be paid at least 2 days before the trip departure.",
      "After the payment is completed, please share your ID proof and email address.",
      "A confirmation email will be sent to you once all the details are received.",
    ],
    thingsToCarry: [
      "Sunglasses: Ensure you have a high-quality pair to shield your eyes from UV rays.",
      "Towel: A compact, quick-drying towel is ideal for travel.",
      "Water Bottle and Thermos Flask: Stay hydrated and keep your beverages at the desired temperature.",
      "Umbrella: A sturdy, travel-friendly umbrella for sudden rain showers.",
      "Raincoat, Poncho, and Windcheater Jackets: Layer up with waterproof and windproof gear to stay dry and warm in varying weather conditions.",
      "Hiking Shoes: Invest in a durable, comfortable pair suitable for long walks and uneven terrain.",
      "Socks and Gloves: Carry at least two pairs of each for warmth and comfort.",
      "Fleece and Thermal Pants: Essential for insulation against the cold.",
      "T-Shirts: Bring a mix of lightweight and thermal options to accommodate different climates.",
      "Sunscreen and Moisturizer: Protect your skin from harsh sun and dry air.",
      "Medications: Pack personal medications, including those for common issues like gas and headaches.",
      "Toiletries: Include all necessary items for personal hygiene.",
      "Dry Fruits: A healthy, energy-boosting snack that is easy to carry.",
      "Protein Bars: Convenient and nutritious options to keep your energy levels up during activities.",
    ],
} satisfies TripDetail